development:
  password: shptka_03583c0631c86f75bdb63fbf9da5dedc
  theme_id: "136586363116"
  store: perseperse.myshopify.com


shopify theme pull
shopify theme serve
theme get --list -p=shptka_03583c0631c86f75bdb63fbf9da5dedc -s=perseperse.myshopify.com

